FROM ubuntu:20.04

RUN apt-get update

RUN apt-get install git python3 pip tar wget -y

# Setup gcc toolchain
RUN wget https://developer.arm.com/-/media/Files/downloads/gnu-rm/10.3-2021.10/gcc-arm-none-eabi-10.3-2021.10-x86_64-linux.tar.bz2
RUN tar -xjvf gcc-arm-none-eabi-10.3-2021.10-x86_64-linux.tar.bz2
ENV PATH="$PATH:/gcc-arm-none-eabi-10.3-2021.10/bin"
RUN echo "$PATH"
# RUN echo 'export PATH=$PATH:/gcc-arm-none-eabi-10.3-2021.10/bin/arm-none-eabi-g++' >> /root/.bashrc 
# RUN /bin/bash -c 'source /root/.bashrc'
#RUN source /etc/bash.bashrc

# Setup Pros
RUN python3 -m pip install pros-cli
RUN pros --use-analytics false

# Entrypoint
# COPY entrypoint.sh /entrypoint.sh
# RUN chmod +x /entrypoint.sh

# Testing
RUN git clone https://github.com/UWST-Robotics/2024-2025-Vex.git

# ENTRYPOINT ["/entrypoint"]
